SET search_path TO projet;


-- Schema

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet;


-- Table Compte
CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	flagadmin		BOOLEAN			NOT NULL	DEFAULT false,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

-- Table Parent
CREATE TABLE parent (
    IdParent INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdCompte INT NOT NULL,
    Nom VARCHAR(255) NOT NULL,
    Prenom VARCHAR(255) NOT NULL,
    Adresse VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Telephone VARCHAR(15),
    FOREIGN KEY (IdCompte) REFERENCES compte(IdCompte),
    PRIMARY KEY(IdParent)
);

-- Table Contrat
CREATE TABLE contrat (
    IdContrat INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdParent INT NOT NULL,
    NomEnfant VARCHAR(255) NOT NULL,
    PrenomEnfant VARCHAR(255) NOT NULL,
    DateNaissance DATE NOT NULL,
    DateDebut DATE NOT NULL,
    DateFin DATE NOT NULL,
    TarifHoraire DECIMAL(5,2) NOT NULL,
    IndemniteTauxHoraire DECIMAL(5,2),
    IndemniteMontantMinimum DECIMAL(5,2),
    IndemniteRepas DECIMAL(5,2),
    FOREIGN KEY (IdParent) REFERENCES parent(IdParent),
    PRIMARY KEY(IdContrat)
);

-- Table Garde
CREATE TABLE garde (
    IdGarde INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdContrat INT NOT NULL,
    date DATE NOT NULL,
    HeureArrivee TIME NOT NULL,
    HeureDepart TIME NOT NULL,
    NombreRepasPris INT,
    FOREIGN KEY (IdContrat) REFERENCES contrat(IdContrat),
    PRIMARY KEY(IdGarde)
);


-- Table Tarifs
CREATE TABLE tarifs (
    IdTarif INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    TauxHoraire DECIMAL(5,2) NOT NULL, -- type qui permet de stocker des valeurs decimales, 2 chiffres apres la virgule
    IndemnitesEntretienTauxHoraire DECIMAL(5,3) NOT NULL,
    IndemnitesEntretienMinJour DECIMAL(5,2) NOT NULL,
    IndemnitesRepas DECIMAL(5,2) NOT NULL, -- les tarifs par defaut à l'ouverture 
    PRIMARY KEY(IdTarif)
);



